// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAL.Database.Database;

namespace TAL.Database.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("TAL.Model.Premium.Occupation", b =>
                {
                    b.Property<int>("OccupationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("RatingId");

                    b.HasKey("OccupationId");

                    b.HasIndex("RatingId");

                    b.ToTable("Occupations");

                    b.HasData(
                        new
                        {
                            OccupationId = 1,
                            Name = "Cleaner",
                            RatingId = 3
                        },
                        new
                        {
                            OccupationId = 2,
                            Name = "Doctor",
                            RatingId = 1
                        },
                        new
                        {
                            OccupationId = 3,
                            Name = "Author",
                            RatingId = 2
                        },
                        new
                        {
                            OccupationId = 4,
                            Name = "Farmer",
                            RatingId = 4
                        },
                        new
                        {
                            OccupationId = 5,
                            Name = "Mechanic",
                            RatingId = 4
                        },
                        new
                        {
                            OccupationId = 6,
                            Name = "Florist",
                            RatingId = 3
                        });
                });

            modelBuilder.Entity("TAL.Model.Premium.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Factor");

                    b.Property<string>("Name");

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Factor = 1.0m,
                            Name = "Professional"
                        },
                        new
                        {
                            RatingId = 2,
                            Factor = 1.25m,
                            Name = "White Collar"
                        },
                        new
                        {
                            RatingId = 3,
                            Factor = 1.50m,
                            Name = "Light Manual"
                        },
                        new
                        {
                            RatingId = 4,
                            Factor = 1.75m,
                            Name = "Heavy Manual"
                        });
                });

            modelBuilder.Entity("TAL.Model.Premium.Occupation", b =>
                {
                    b.HasOne("TAL.Model.Premium.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
